
// Condition mapping → List of prohibited nutrients
const conditionMap = {
    Diabetes: ['Total Sugars', 'Sugars, total'],
    Hypertension: ['Sodium, Na', 'Sodium'],
    CKD: ['Potassium'],
    Hyperlipidemia: ['Total lipid (fat)', 'Cholesterol'],
    Gout: ['Purine', 'Uric acid'],
    'Celiac Disease': ['Gluten'],
    'Lactose Intolerance': ['Lactose'],
    Anemia: ['Tannins', 'Calcium (in excess)'],
    Osteoporosis: ['Sodium', 'Caffeine'],
    'Heart Failure': ['Sodium', 'Fluid'],
    Obesity: ['Total Sugars', 'Total lipid (fat)', 'Calories'],
    Gallstones: ['Cholesterol', 'Total lipid (fat)'],
    Pancreatitis: ['Total lipid (fat)', 'Alcohol'],
    'Fatty Liver': ['Total lipid (fat)', 'Alcohol'],
    IBS: ['FODMAPs', 'Lactose'],
    PKU: ['Phenylalanine', 'Aspartame'],
    Hemochromatosis: ['Iron'],
    "Wilson's Disease": ['Copper'],
    'Kidney Stones': ['Oxalate', 'Calcium (in excess)', 'Sodium'],
    Hypothyroidism: ['Goitrogens', 'Soy'],
    Hyperthyroidism: ['Iodine'],
    GERD: ['Caffeine', 'Chocolate', 'Spicy foods'],
    'Peptic Ulcer': ['NSAIDs', 'Alcohol'],
    Diverticulitis: ['Seeds', 'Nuts'],
    "Crohn's Disease": ['Fiber (during flare)'],
    'Ulcerative Colitis': ['Lactose', 'Fiber (during flare)'],
    Migraine: ['Tyramine', 'Nitrates', 'MSG'],
    Asthma: ['Sulfites'],
    'Allergy - Peanut': ['Peanuts'],
    'Allergy - Tree Nut': ['Tree nuts'],
    'Allergy - Egg': ['Egg'],
    'Allergy - Fish': ['Fish'],
    'Allergy - Shellfish': ['Shellfish'],
    'Allergy - Soy': ['Soy'],
    'Allergy - Wheat': ['Wheat'],
    'Allergy - Sesame': ['Sesame'],
    'Allergy - Milk': ['Milk'],
    'Allergy - Mustard': ['Mustard'],
    'Allergy - Celery': ['Celery'],
    'Allergy - Lupin': ['Lupin'],
    'Allergy - Sulfite': ['Sulfites'],
    'Allergy - Mollusk': ['Mollusks'],
    'Allergy - Gluten': ['Gluten'],
    'Allergy - Corn': ['Corn'],
    'Allergy - Strawberry': ['Strawberry'],
    'Allergy - Tomato': ['Tomato'],
    'Allergy - Citrus': ['Citrus'],
    'Allergy - Banana': ['Banana'],
    'Allergy - Apple': ['Apple'],
    'Allergy - Kiwi': ['Kiwi'],
    'Allergy - Avocado': ['Avocado'],
    'Allergy - Garlic': ['Garlic'],
    'Allergy - Onion': ['Onion'],
    'Allergy - Chocolate': ['Chocolate'],
    'Allergy - Cocoa': ['Cocoa'],
    'Allergy - Pine Nut': ['Pine nut'],
    'Allergy - Sunflower': ['Sunflower'],
    'Allergy - Poppy Seed': ['Poppy seed'],
    'Allergy - Mustard Seed': ['Mustard seed'],
    'Allergy - Sesame Seed': ['Sesame seed'],
    'Allergy - Buckwheat': ['Buckwheat'],
    'Allergy - Lentil': ['Lentil'],
    'Allergy - Chickpea': ['Chickpea'],
    'Allergy - Pea': ['Pea'],
    'Allergy - Bean': ['Bean'],
    'Allergy - Soybean': ['Soybean'],
    'Allergy - Barley': ['Barley'],
    'Allergy - Rye': ['Rye'],
    'Allergy - Oat': ['Oat'],
    'Allergy - Spelt': ['Spelt'],
    'Allergy - Kamut': ['Kamut'],
    'Allergy - Quinoa': ['Quinoa'],
    'Allergy - Amaranth': ['Amaranth'],
    'Allergy - Millet': ['Millet'],
    'Allergy - Sorghum': ['Sorghum'],
    'Allergy - Teff': ['Teff'],
    'Allergy - Triticale': ['Triticale'],
    'Allergy - Farro': ['Farro'],
    'Allergy - Freekeh': ['Freekeh'],
    'Allergy - Emmer': ['Emmer'],
    'Allergy - Einkorn': ['Einkorn'],
    'Allergy - Spelt Wheat': ['Spelt wheat'],
    'Allergy - Durum Wheat': ['Durum wheat'],
    'Allergy - Semolina': ['Semolina'],
    'Allergy - Couscous': ['Couscous'],
    'Allergy - Bulgur': ['Bulgur'],
    'Allergy - Seitan': ['Seitan'],
    'Allergy - Tempeh': ['Tempeh'],
    'Allergy - Tofu': ['Tofu'],
    'Allergy - Miso': ['Miso'],
    'Allergy - Natto': ['Natto'],
    'Allergy - Edamame': ['Edamame'],
    'Allergy - Textured Vegetable Protein': ['Textured vegetable protein'],
    'Allergy - Hydrolyzed Vegetable Protein': ['Hydrolyzed vegetable protein'],
    'Allergy - Lecithin': ['Lecithin'],
    'Allergy - Casein': ['Casein'],
    'Allergy - Whey': ['Whey'],
    'Allergy - Lactalbumin': ['Lactalbumin'],
    'Allergy - Lactoglobulin': ['Lactoglobulin'],
    'Allergy - Albumin': ['Albumin'],
    'Allergy - Ovalbumin': ['Ovalbumin'],
    'Allergy - Ovomucoid': ['Ovomucoid'],
    'Allergy - Lysozyme': ['Lysozyme'],
    'Allergy - Ovotransferrin': ['Ovotransferrin'],
    'Allergy - Ovovitellin': ['Ovovitellin'],
    'Allergy - Ovovitelin': ['Ovovitelin'],
    'Allergy - Ovoglobulin': ['Ovoglobulin'],
    'Allergy - Ovomucin': ['Ovomucin'],
    'Allergy - Ovomacroglobulin': ['Ovomacroglobulin'],
    'Allergy - Ovomucinoid': ['Ovomucinoid'],
    'Allergy - Ovomucinase': ['Ovomucinase'],
    'Allergy - Ovomucoprotein': ['Ovomucoprotein'],
    'Allergy - Ovomucoprotease': ['Ovomucoprotease'],
    'Allergy - Ovomucoproteinase': ['Ovomucoproteinase'],
    'Allergy - Ovomucoproteinase inhibitor': ['Ovomucoproteinase inhibitor'],
    'Allergy - Almond': ['Almond'],
    'Allergy - Walnut': ['Walnut'],
    'Allergy - Hazelnut': ['Hazelnut'],
    'Allergy - Cashew': ['Cashew'],
    'Allergy - Pistachio': ['Pistachio'],
    'Allergy - Macadamia': ['Macadamia nut'],
    'Allergy - Brazil Nut': ['Brazil nut'],
    'Allergy - Chestnut': ['Chestnut'],
    'Allergy - Pecan': ['Pecan'],
    'Allergy - Walnut Oil': ['Walnut oil'],
    'Allergy - Almond Oil': ['Almond oil'],
    'Allergy - Soy Sauce': ['Soy sauce'],
    'Allergy - Wheat Starch': ['Wheat starch'],
    'Allergy - Gluten Starch': ['Gluten starch'],
    'Allergy - Egg White': ['Egg white'],
    'Allergy - Egg Yolk': ['Egg yolk'],
    'Allergy - Fish Oil': ['Fish oil'],
    'Allergy - Shellfish Extract': ['Shellfish extract'],
    'Allergy - Shrimp': ['Shrimp'],
    'Allergy - Crab': ['Crab'],
    'Allergy - Lobster': ['Lobster'],
    'Allergy - Mussel': ['Mussel'],
    'Allergy - Clam': ['Clam'],
    'Allergy - Oyster': ['Oyster'],
    'Allergy - Scallop': ['Scallop'],
    'Allergy - Squid': ['Squid'],
    'Allergy - Octopus': ['Octopus'],
    'Allergy - Snail': ['Snail'],
    'Allergy - Abalone': ['Abalone'],
    'Allergy - Anchovy': ['Anchovy'],
    'Allergy - Sardine': ['Sardine'],
    'Allergy - Tuna': ['Tuna'],
    'Allergy - Salmon': ['Salmon'],
    'Allergy - Mackerel': ['Mackerel'],
    'Allergy - Herring': ['Herring'],
    'Allergy - Trout': ['Trout'],
    'Allergy - Cod': ['Cod'],
    'Allergy - Pollock': ['Pollock'],
    'Allergy - Haddock': ['Haddock'],
    'Allergy - Tilapia': ['Tilapia'],
    'Allergy - Catfish': ['Catfish'],
    'Allergy - Carp': ['Carp'],
    'Allergy - Eel': ['Eel'],
    'Allergy - Swordfish': ['Swordfish'],
    'Allergy - Shark': ['Shark'],
    'Allergy - Roe': ['Roe'],
    'Allergy - Caviar': ['Caviar'],
    'Allergy - Milk Protein': ['Milk protein'],
    'Allergy - Goat Milk': ['Goat milk'],
    'Allergy - Sheep Milk': ['Sheep milk'],
    'Allergy - Buffalo Milk': ['Buffalo milk'],
    'Allergy - Camel Milk': ['Camel milk'],
    'Allergy - Cow Milk': ['Cow milk'],
    'Allergy - Caseinate': ['Caseinate'],
    'Allergy - Skim Milk': ['Skim milk'],
    'Allergy - Whole Milk': ['Whole milk'],
    'Allergy - Yogurt': ['Yogurt'],
    'Allergy - Cheese': ['Cheese'],
    'Allergy - Butter': ['Butter'],
    'Allergy - Cream': ['Cream'],
    'Allergy - Ice Cream': ['Ice cream'],
    'Allergy - Kefir': ['Kefir'],
    'Allergy - Buttermilk': ['Buttermilk'],
    'Allergy - Ghee': ['Ghee'],
    'Allergy - Paneer': ['Paneer'],
    'Allergy - Ricotta': ['Ricotta'],
    'Allergy - Mozzarella': ['Mozzarella'],
    'Allergy - Parmesan': ['Parmesan'],
    'Allergy - Feta': ['Feta'],
    'Allergy - Blue Cheese': ['Blue cheese'],
    'Allergy - Brie': ['Brie'],
    'Allergy - Camembert': ['Camembert'],
    'Allergy - Cheddar': ['Cheddar'],
    'Allergy - Gouda': ['Gouda'],
    'Allergy - Swiss Cheese': ['Swiss cheese'],
    'Allergy - Edam': ['Edam'],
    'Allergy - Emmental': ['Emmental'],
    'Allergy - Gruyere': ['Gruyere'],
    'Allergy - Provolone': ['Provolone'],
    'Allergy - Roquefort': ['Roquefort'],
    'Allergy - Stilton': ['Stilton'],
    'Allergy - Cottage Cheese': ['Cottage cheese'],
    'Allergy - Cream Cheese': ['Cream cheese'],
    'Allergy - Quark': ['Quark'],
    'Allergy - Mascarpone': ['Mascarpone'],
    'Allergy - Fromage Blanc': ['Fromage blanc'],
    'Allergy - Limburger': ['Limburger'],
    'Allergy - Tilsit': ['Tilsit'],
    'Allergy - Havarti': ['Havarti'],
    'Allergy - Monterey Jack': ['Monterey Jack'],
    'Allergy - Colby': ['Colby'],
    'Allergy - Muenster': ['Muenster'],
    'Allergy - Pepper Jack': ['Pepper Jack'],
    'Allergy - Asiago': ['Asiago'],
    'Allergy - Pecorino': ['Pecorino'],
    'Allergy - Manchego': ['Manchego'],
    'Allergy - Cotija': ['Cotija'],
    'Allergy - Oaxaca': ['Oaxaca'],
    'Allergy - Queso Fresco': ['Queso fresco'],
    'Allergy - Queso Blanco': ['Queso blanco'],
    'Allergy - Halloumi': ['Halloumi'],
    'Allergy - Kasseri': ['Kasseri'],
    'Allergy - Kefalotyri': ['Kefalotyri'],
    'Allergy - Kefalograviera': ['Kefalograviera'],
    'Allergy - Myzithra': ['Myzithra'],
    'Allergy - Ricotta Salata': ['Ricotta salata'],
    'Allergy - Teleme': ['Teleme'],
    'Allergy - Tvorog': ['Tvorog'],
    'Allergy - Vacherin': ['Vacherin'],
    'Allergy - Wensleydale': ['Wensleydale'],
    'Allergy - Yarg': ['Yarg'],
    'Allergy - Zamorano': ['Zamorano'],
    'Allergy - Paneer Tikka': ['Paneer tikka'],
    'Allergy - Labneh': ['Labneh'],
    'Allergy - Dahi': ['Dahi'],
    'Allergy - Ayran': ['Ayran'],
    'Allergy - Lassi': ['Lassi'],
    'Allergy - Chaas': ['Chaas'],
    'Allergy - Smetana': ['Smetana'],
    'Allergy - Clotted Cream': ['Clotted cream'],
    'Allergy - Double Cream': ['Double cream'],
    'Allergy - Single Cream': ['Single cream'],
    'Allergy - Sour Cream': ['Sour cream'],
    'Allergy - Whipped Cream': ['Whipped cream'],
    'Allergy - Evaporated Milk': ['Evaporated milk'],
    'Allergy - Condensed Milk': ['Condensed milk'],
    'Allergy - Powdered Milk': ['Powdered milk'],
    'Allergy - Malted Milk': ['Malted milk'],
    'Allergy - Milk Chocolate': ['Milk chocolate'],
    'Allergy - White Chocolate': ['White chocolate'],
    'Allergy - Dark Chocolate': ['Dark chocolate'],
    'Allergy - Cocoa Butter': ['Cocoa butter'],
    'Allergy - Cocoa Powder': ['Cocoa powder'],
    'Allergy - Carob': ['Carob'],
    'Allergy - Malt': ['Malt'],
    'Allergy - Malt Extract': ['Malt extract'],
    'Allergy - Malt Syrup': ['Malt syrup'],
    'Allergy - Maltodextrin': ['Maltodextrin'],
    'Allergy - Dextrin': ['Dextrin'],
    'Allergy - Dextrose': ['Dextrose'],
    'Allergy - Glucose': ['Glucose'],
    'Allergy - Fructose': ['Fructose'],
    'Allergy - Sucrose': ['Sucrose'],
    'Allergy - Lactose': ['Lactose'],
    'Allergy - Galactose': ['Galactose'],
    'Allergy - Mannitol': ['Mannitol'],
    'Allergy - Sorbitol': ['Sorbitol'],
    'Allergy - Xylitol': ['Xylitol'],
    'Allergy - Erythritol': ['Erythritol'],
    'Allergy - Isomalt': ['Isomalt'],
    'Allergy - Maltitol': ['Maltitol'],
    'Allergy - Polydextrose': ['Polydextrose'],
    'Allergy - Inulin': ['Inulin'],
    'Allergy - Oligofructose': ['Oligofructose'],
    'Allergy - FOS': ['Fructooligosaccharides'],
    'Allergy - GOS': ['Galactooligosaccharides'],
    'Allergy - Trehalose': ['Trehalose'],
    'Allergy - Tagatose': ['Tagatose'],
    'Allergy - Stevia': ['Stevia'],
    'Allergy - Monk Fruit': ['Monk fruit'],
    'Allergy - Sucralose': ['Sucralose'],
    'Allergy - Aspartame': ['Aspartame'],
    'Allergy - Acesulfame K': ['Acesulfame K'],
    'Allergy - Saccharin': ['Saccharin'],
    'Allergy - Cyclamate': ['Cyclamate'],
    'Allergy - Neotame': ['Neotame'],
    'Allergy - Advantame': ['Advantame'],
    'Allergy - Alitame': ['Alitame'],
    'Allergy - Thaumatin': ['Thaumatin'],
    'Allergy - Glycyrrhizin': ['Glycyrrhizin'],
    'Allergy - Sorghum Syrup': ['Sorghum syrup'],
    'Allergy - Maple Syrup': ['Maple syrup'],
    'Allergy - Agave Syrup': ['Agave syrup'],
    'Allergy - Honey': ['Honey'],
    'Allergy - Molasses': ['Molasses'],
    'Allergy - Corn Syrup': ['Corn syrup'],
    'Allergy - High Fructose Corn Syrup': ['High fructose corn syrup'],
    'Allergy - Brown Rice Syrup': ['Brown rice syrup'],
    'Allergy - Barley Malt Syrup': ['Barley malt syrup'],
    'Allergy - Date Syrup': ['Date syrup'],
    'Allergy - Coconut Sugar': ['Coconut sugar'],
    'Allergy - Palm Sugar': ['Palm sugar'],
    'Allergy - Beet Sugar': ['Beet sugar'],
    'Allergy - Cane Sugar': ['Cane sugar'],
    'Allergy - Raw Sugar': ['Raw sugar'],
    'Allergy - Turbinado Sugar': ['Turbinado sugar'],
    'Allergy - Demerara Sugar': ['Demerara sugar'],
    'Cystic Fibrosis': ['Sodium', 'Fat (in excess)'],
    Phenylketonuria: ['Phenylalanine'],
    'Fructose Intolerance': ['Fructose', 'Sucrose'],
    Galactosemia: ['Galactose', 'Lactose'],
    'Maple Syrup Urine Disease': ['Leucine', 'Isoleucine', 'Valine'],
    Tyrosinemia: ['Tyrosine', 'Phenylalanine'],
    Homocystinuria: ['Methionine'],
    "Reye's Syndrome": ['Aspirin'],
    Porphyria: ['Alcohol', 'Barbiturates'],
    Cystinuria: ['Cystine'],
    'G6PD Deficiency': ['Fava beans', 'Naphthalene', 'Sulfa drugs'],
    'Histamine Intolerance': ['Histamine', 'Aged cheese', 'Cured meats'],
    'Salicylate Sensitivity': ['Salicylates'],
    'Sulfite Sensitivity': ['Sulfites'],
    'FODMAP Intolerance': ['FODMAPs'],
    'Lipid Storage Disease': ['Fat (in excess)'],
    'Primary Biliary Cholangitis': ['Fat (in excess)'],
    'Primary Sclerosing Cholangitis': ['Fat (in excess)'],
    'Short Bowel Syndrome': ['Fat (in excess)', 'Lactose'],
    'Dumping Syndrome': ['Simple sugars'],
    Cystinosis: ['Cystine'],
    Alkaptonuria: ['Phenylalanine', 'Tyrosine'],
    Albinism: ['Tyrosine'],
    'Wilson Disease': ['Copper'],
    Hemochromatosis: ['Iron'],
    "Menkes Disease": ['Copper'],
    "Hartnup Disease": ['Tryptophan'],
    'Propionic Acidemia': ['Valine', 'Isoleucine', 'Methionine', 'Threonine'],
    'Methylmalonic Acidemia': ['Valine', 'Isoleucine', 'Methionine', 'Threonine'],
    'Urea Cycle Disorder': ['Protein (in excess)'],
    'Ornithine Transcarbamylase Deficiency': ['Protein (in excess)'],
    Citrullinemia: ['Protein (in excess)'],
    'Argininosuccinic Aciduria': ['Protein (in excess)'],
    'Lysinuric Protein Intolerance': ['Protein (in excess)'],
    'MCAD Deficiency': ['Fasting', 'Medium-chain triglycerides'],
    'Carnitine Deficiency': ['Long-chain fatty acids'],
    'Glycogen Storage Disease': ['Sucrose', 'Lactose', 'Fructose', 'Galactose'],
    'Hereditary Fructose Intolerance': ['Fructose', 'Sucrose', 'Sorbitol'],
    'Classic Galactosemia': ['Galactose', 'Lactose'],
    'Citrin Deficiency': ['Carbohydrates (in excess)'],
    'Pyruvate Dehydrogenase Deficiency': ['Carbohydrates (in excess)'],
    'Glucose-6-Phosphatase Deficiency': ['Sucrose', 'Lactose', 'Fructose', 'Galactose'],
    'Maple Syrup Urine Disease': ['Leucine', 'Isoleucine', 'Valine'],
    'Isovaleric Acidemia': ['Leucine'],
    'Glutaric Acidemia Type I': ['Lysine', 'Tryptophan', 'Hydroxylysine'],
    'Methylmalonic Acidemia': ['Methionine', 'Threonine', 'Valine', 'Isoleucine'],
    'Propionic Acidemia': ['Methionine', 'Threonine', 'Valine', 'Isoleucine'],
    'Tyrosinemia Type I': ['Tyrosine', 'Phenylalanine'],
    'Tyrosinemia Type II': ['Tyrosine'],
    'Tyrosinemia Type III': ['Tyrosine'],
    Homocystinuria: ['Methionine'],
    Cystathioninuria: ['Methionine'],
    Phenylketonuria: ['Phenylalanine'],
    Alkaptonuria: ['Phenylalanine', 'Tyrosine'],
    'Glycine Encephalopathy': ['Glycine'],
    'Nonketotic Hyperglycinemia': ['Glycine'],
    'Classic PKU': ['Phenylalanine'],
    'Maternal PKU': ['Phenylalanine'],
    Hyperprolinemia: ['Proline'],
    Hyperornithinemia: ['Ornithine'],
    Hyperargininemia: ['Arginine'],
    Hyperlysinemia: ['Lysine'],
    Hyperammonemia: ['Protein (in excess)'],
    Citrullinemia: ['Protein (in excess)'],
    'Argininosuccinic Aciduria': ['Protein (in excess)'],
    'Ornithine Transcarbamylase Deficiency': ['Protein (in excess)'],
    'Carbamoyl Phosphate Synthetase Deficiency': ['Protein (in excess)'],
    'N-Acetylglutamate Synthetase Deficiency': ['Protein (in excess)'],
    'Lysinuric Protein Intolerance': ['Protein (in excess)'],
    Hyperinsulinism: ['Simple sugars'],
    'Congenital Adrenal Hyperplasia': ['Salt (in excess)'],
    'Congenital Hypothyroidism': ['Goitrogens'],
    'Congenital Lactase Deficiency': ['Lactose'],
    'Congenital Sucrase-Isomaltase Deficiency': ['Sucrose', 'Isomaltose'],
    'Congenital Fructose Intolerance': ['Fructose', 'Sucrose', 'Sorbitol'],
    'Congenital Glucose-Galactose Malabsorption': ['Glucose', 'Galactose'],
    'Congenital Chloride Diarrhea': ['Salt (in excess)'],
    'Congenital Bile Acid Synthesis Defect': ['Fat (in excess)'],
    'Congenital Disorders of Glycosylation': ['Mannose'],
    'Congenital Neutropenia': ['Raw foods (risk of infection)'],
    'Congenital Erythropoietic Porphyria': ['Sunlight', 'Certain drugs'],
    'Congenital Methemoglobinemia': ['Nitrates'],
    'Congenital Hyperammonemia': ['Protein (in excess)'],
    'Congenital Hyperinsulinism': ['Simple sugars'],
    'Congenital Hypercholesterolemia': ['Cholesterol', 'Saturated fat'],
    'Congenital Hypertriglyceridemia': ['Fat (in excess)', 'Simple sugars'],
    'Congenital Hypoaldosteronism': ['Potassium (in excess)'],
    'Congenital Adrenal Insufficiency': ['Salt (in excess)'],
    'Congenital Nephrotic Syndrome': ['Salt (in excess)', 'Protein (in excess)'],
    'Congenital Heart Disease': ['Salt (in excess)', 'Fat (in excess)'],
    'Congenital Liver Disease': ['Fat (in excess)'],
    'Congenital Pancreatic Insufficiency': ['Fat (in excess)'],
    'Congenital Renal Tubular Acidosis': ['Salt (in excess)'],
    'Congenital Myasthenic Syndrome': ['Magnesium (in excess)'],
    'Congenital Myopathy': ['Fat (in excess)'],
    'Congenital Muscular Dystrophy': ['Fat (in excess)'],
    'Congenital Hypotonia': ['Fat (in excess)'],
    'Congenital Hypertonia': ['Salt (in excess)'],
    'Congenital Spasticity': ['Salt (in excess)'],
    'Congenital Ataxia': ['Alcohol'],
    'Congenital Dystonia': ['Alcohol'],
    'Congenital Tremor': ['Caffeine'],
    'Congenital Chorea': ['Caffeine'],
    'Congenital Tics': ['Caffeine'],
    'Congenital Seizure Disorder': ['Caffeine', 'Alcohol'],
    'Congenital Migraine': ['Tyramine', 'Nitrates', 'MSG'],
    'Congenital Cluster Headache': ['Alcohol'],
    'Congenital Tension Headache': ['Caffeine'],
    'Congenital Neuralgia': ['Alcohol'],
    'Congenital Neuropathy': ['Alcohol'],
    'Congenital Myelopathy': ['Alcohol'],
    'Congenital Encephalopathy': ['Alcohol'],
    'Congenital Dementia': ['Alcohol'],
    'Congenital Amnesia': ['Alcohol'],
    'Congenital Aphasia': ['Alcohol'],
    'Congenital Apraxia': ['Alcohol'],
    'Congenital Agnosia': ['Alcohol'],
    'Congenital Alexia': ['Alcohol'],
    'Congenital Agraphia': ['Alcohol'],
    'Congenital Dyslexia': ['Alcohol'],
    'Congenital Dyscalculia': ['Alcohol'],
    'Congenital Dysgraphia': ['Alcohol'],
    'Congenital Dyspraxia': ['Alcohol'],
    'Congenital Dysphasia': ['Alcohol'],
    'Congenital Dysarthria': ['Alcohol'],
    'Congenital Dysphagia': ['Alcohol'],
    'Congenital Dysphonia': ['Alcohol'],
    'Congenital Dysmetria': ['Alcohol'],
    'Congenital Dysdiadochokinesia': ['Alcohol'],
    'Congenital Dysesthesia': ['Alcohol'],
    'Congenital Dysgeusia': ['Alcohol'],
    'Congenital Dysosmia': ['Alcohol'],
    'Congenital Dyschromatopsia': ['Alcohol'],
    'Congenital Dysacusis': ['Alcohol'],
    'Congenital Dysphoria': ['Alcohol'],
    'Congenital Dysthymia': ['Alcohol'],
    'Congenital Dystonia': ['Alcohol'],
    'Congenital Dystrophy': ['Alcohol'],
    'Congenital Dystrophy of Retina': ['Alcohol'],
    'Congenital Dystrophy of Muscle': ['Alcohol'],
    'Congenital Dystrophy of Bone': ['Alcohol'],
    'Congenital Dystrophy of Skin': ['Alcohol'],
    'Congenital Dystrophy of Hair': ['Alcohol'],
    'Congenital Dystrophy of Nail': ['Alcohol'],
    'Congenital Dystrophy of Tooth': ['Alcohol'],
    'Congenital Dystrophy of Cartilage': ['Alcohol'],
    'Congenital Dystrophy of Connective Tissue': ['Alcohol'],
    'Congenital Dystrophy of Blood': ['Alcohol'],
    'Congenital Dystrophy of Lymph': ['Alcohol'],
    'Congenital Dystrophy of Endocrine Gland': ['Alcohol'],
    'Congenital Dystrophy of Exocrine Gland': ['Alcohol'],
    'Congenital Dystrophy of Nervous System': ['Alcohol'],
    'Congenital Dystrophy of Immune System': ['Alcohol'],
    'Congenital Dystrophy of Reproductive System': ['Alcohol'],
    'Congenital Dystrophy of Urinary System': ['Alcohol'],
    'Congenital Dystrophy of Digestive System': ['Alcohol'],
    'Congenital Dystrophy of Respiratory System': ['Alcohol'],
    'Congenital Dystrophy of Circulatory System': ['Alcohol'],
    'Congenital Dystrophy of Musculoskeletal System': ['Alcohol'],
    'Congenital Dystrophy of Integumentary System': ['Alcohol'],
    'Congenital Dystrophy of Sensory System': ['Alcohol'],
    'Congenital Dystrophy of Other System': ['Alcohol'],
};

/**
 * Returns warning messages for given conditions and nutrients.
 * @param {string[]} conditions - List of medical conditions.
 * @param {Record<string, number>} nutrients - Nutrient values by name.
 * @param {string} itemName - Name of the food item (for allergy checks).
 * @returns {string[]} Array of warning messages.
 */
function getWarningsForProfile(conditions, nutrients, itemName) {
    if (!Array.isArray(conditions) || typeof nutrients !== 'object') {
        return [];
    }

    const warnings = new Set();
    const nutrientKeys = Object.keys(nutrients || {});

    // 1) Nutrient testing
  for (const condition of conditions) {
    const forbiddenNutrients = conditionMap[condition];
    if (!forbiddenNutrients) continue;

    for (const forbidden of forbiddenNutrients) {
      const matched = nutrientKeys.find(
        key => key.toLowerCase() === forbidden.toLowerCase()
      );
      if (matched && nutrients[matched] != null) {
        warnings.add(`⚠️ ${condition}: contains ${forbidden}`);
      }
    }
  }

  // 2) Allergy testing for the food itself
  for (const condition of conditions) {
    if (condition.startsWith('Allergy - ')) {
      const allergen = condition.slice('Allergy - '.length).toLowerCase();
      if (typeof itemName === 'string' &&
          itemName.toLowerCase().includes(allergen)
      ) {
        warnings.add(`⚠️ ${condition}: allergic to ${itemName}`);
      }
    }
  }

  return Array.from(warnings);
}

module.exports = { getWarningsForProfile };